version: "3.8"


services:
  cypress:
    build: .
    container_name: teste_automatizados_cypress_api
    environment:
      CYPRESS_baseUrl: "https://desenvolvimento.pje.csjt.jus.br/pje-seguranca/api/"
    volumes:
      - .:/app
    working_dir: /app
    command: ["cypress", "run"]